stages:
  - build
  - test

cache:

  paths:
    - node_modules/

install packages:

  image: node:latest

  stage: build
  
  script:
    - apt-get update
    - apt-get install wget -y
    - PLAYWRIGHT_BROWSERS_PATH=0
    - npm ci

  only:
    - feature/gitlab

playwright test:

  image: mcr.microsoft.com/playwright:focal

  stage: test
  
  script:
    - nohup npm run start &
    - npx playwright install
    - npx playwright install chrome
    - npm run pw:test

  only:
    - feature/gitlab

cypress test:

  image: cypress/browsers:node12.14.1-chrome85-ff81

  stage: test
  
  script:
    - nohup npm run start &
    - npm run cy:test

  only:
    - feature/gitlab
