stages:
  - build
  - test

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline


install modules:

  image: node:latest

  stage: build
  
  script:
    - npm ci

  only:
    - feature/gitlab

playwright test:

  image: mcr.microsoft.com/playwright:focal

  stage: test

  script:
    - apt-get update
    - apt-get install wget -y
    - PLAYWRIGHT_BROWSERS_PATH=0
    - nohup npm run start &
    - npx playwright install
    - npx playwright install chrome
    - npm run test:cy

  only:
    - feature/gitlab

cypress test:

  image: cypress/browsers:node12.14.1-chrome85-ff81

  stage: test
  
  script:
    - nohup npm run start &
    - npm run test:cy

  only:
    - feature/gitlab
