stages:
  # - cypress_test
  
  - playwright_test
     
cache:

  paths:
    - node_modules/
    - $HOME/.npm
    - ~/.cache/ms-playwright


playwright:test:

  image: mcr.microsoft.com/playwright:focal

  stage: playwright_test
  
  script:
    - apt-get update
    - apt-get install wget -y
    - PLAYWRIGHT_BROWSERS_PATH=0
    - npm ci
    - nohup npm run start &
    - npx playwright install
    - npx playwright install chrome
    - npm run pw-test

  only:
    - feature/gitlab

# cypress:test:

#   image: cypress/browsers:node12.14.1-chrome85-ff81

#   stage: cypress_test
  
#   script:
#     - npm ci
#     - nohup npm run start &
#     - npm run cp-test

#   only:
#     - feature/gitlab
